### ISSUE TITLE
x86跨架构mips64el不成功

### ISSUE THREAD

**Issue by Avenger-285714** [deepin-community/qemu#8]
以UOS专业版1055为例，安装时固件选择loongson3-virt,发现固件不能正常加载：

`无法完成安装：'内部错误：连接监控的过程中进程退出: 2024-01-28T15:13:57.903388Z qemu-system-mips64el: Could not load MIPS bios '(null)''

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4523, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: 内部错误：连接监控的过程中进程退出: 2024-01-28T15:13:57.903388Z qemu-system-mips64el: Could not load MIPS bios '(null)'
`

同时，该包似乎缺少龙芯mips架构loongson3a和7a的固件（可以从loongnix等发行版获取）

**Comment by RevySR** [comment]
deepin v23似乎没有计划维护mips64el

**Comment by chenchongbiao** [comment]
deepin 不做 mips 相关的支持。并且上游貌似也是损坏状态。
